### ISSUE TITLE
http://localhost:8080/ does not show anything

### ISSUE THREAD

**Issue by simonh1000** [abenz1267/LitElement-TypeScript-and-Webpack-Example#1] opened 2019-10-10 19:01 UTC
i downloaded, did npm install, and npm run dev, and then went to the url above. Nothing could be accessed.

Perhaps add some instructions to the README

Is an index.html missing from the repo?

**Comment by abenz1267** [comment] 2019-10-12 20:29
Hi,

thanks for your notice. "Nothing could be accessed" isn't something I can troubleshoot though. The index.html is in the dist folder.

Nevertheless added the install instruction to the readme as you suggested. Tested on 2 different linux systems just now to make sure... no issues here.

Closing as I can't reproduce it without more information.

Regards

**Closed as completed** 2019-10-12 20:38 UTC

**Comment by simonh1000** [comment] 2019-10-13 08:09
My apologies. I was caught out by the reliance on index.html in the dist directory

**Comment by abenz1267** [comment] 2019-10-13 09:14
No worries. I've moved the index.html to the src folder now.
